{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "be.fullname" . }}-config
  labels:
    {{- include "be.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
{{- end }}