{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "be.fullname" . }}-secret
  labels:
    {{- include "be.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
{{- end }}